name: Setup tldraw/tldraw
description: Set up node & pnpm

runs:
  using: composite
  steps:
    - name: Install pnpm
      run: npm i -g pnpm@9.15.4
      shell: bash

    - name: Setup Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: 22.16.0
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
