name: Setup tldraw/tldraw
description: Set up node & pnpm

runs:
  using: composite
  steps:
    # see https://github.com/actions/setup-node/issues/899 for one of the reasons why this
    # needs to be done before action/setup-node
    - name: Enable corepack
      run: corepack enable
      shell: bash

    - name: Setup Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.0
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
